### PR TITLE
Quarkus fixes

### PR DESCRIPTION
**Pull request by Sanne**
Hi @FroMage,

this is what I have so far.. could you maybe produce some fresh figures?

I'm going to do it as well, then hope to discuss with you ;)

### CODE REVIEW

**Comment by FroMage** [comment]
How about you fix the conflicts? :)

**Comment by Sanne** [comment]
@FroMage oh, ok. I didn't know there was any ;)

**Comment by Sanne** [comment]
@FroMage done!

**Comment by FroMage** [comment]
Thanks!

**Pull request merged**
